### PR TITLE
The 'em' CSS unit can be a float

### PR DESCRIPTION
**Pull request by gahr**
Signed-off-by: Pietro Cerutti <gahr@gahr.ch>

### CODE REVIEW

**Comment by TyOverby** [comment]
Sadly, this would be a breaking change, and I don't think that the benefit would be worth the churn.  How about adding `Em_float` and `Px_float` to the type?

**Comment by gahr** [comment]
That’d work for me

**Comment by gahr** [comment]
However, I can’t find the spot where the css spec states which units support a floating point value. I guess it’s all of them? Should we perhaps add a `_float` variant to all units?

**Comment by TyOverby** [comment]
Yeah, I think that all of the values deserve _float variants

**Pull request closed without merging**
